#!/bin/bash

function ask_yesno {
    read -p "$1 (Y/n)" answer
    case ${answer:0:1} in
        n|N )
            return 1
            ;;
        * )
            return 0
            ;;
    esac
}

if ! ask_yesno 'This script may overwrite any existent file. Continue?'; then
    exit 1
fi

_pwd=$(pwd)

if ask_yesno 'Prefer symlink to copy? Note that this has no effect on ~/.gitignore and bash dotfiles'; then
    _install='ln -svf'
    _install_dir='ln -svf'
else
    _install='cp -fv'
    _install_dir='cp -frv'
fi

if ask_yesno 'Install zsh dotfiles? This will overwrite ~/.zshrc and ~/.zsh-custom'; then
    $_install "$_pwd/zsh/zshrc" "$HOME/.zshrc"
    rm -rvf "$HOME/.zsh-custom" && $_install_dir "$_pwd/zsh/zsh-custom" "$HOME/.zsh-custom"
    touch "$HOME/.zsh-custom/custom.zsh"
fi

if ask_yesno 'Install bash dotfiles? This will override ~/.bash_profile and ~/.bashrc'; then
    cp -fv "$_pwd/bash/bash_profile" "$HOME/.bash_profile"
    cp -fv "$_pwd/bash/bashrc" "$HOME/.bashrc"
fi

if ask_yesno 'Install vim dotfiles? This will overwrite ~/.vimrc{,-common,-commonplugins,-gui,-simple}'; then
    $_install "$_pwd/vim/vimrc" "$HOME/.vimrc"
    $_install "$_pwd/vim/vimrc-common" "$HOME/.vimrc-common"
    $_install "$_pwd/vim/vimrc-commonplugins" "$HOME/.vimrc-commonplugins"
    $_install "$_pwd/vim/vimrc-gui" "$HOME/.vimrc-gui"
    $_install "$_pwd/vim/vimrc-simple" "$HOME/.vimrc-simple"
    if ask_yesno 'Install plugins for vim?'; then
        if ! type git > /dev/null 2>&1; then
            echo 'git not found, skipping'
        elif ! type vim > /dev/null 2>&1; then
            echo 'vim not found, skipping'
        else
            _vundle_path="$HOME/.vim/bundle/Vundle.vim"
            if ! [[ -e "$_vundle_path" ]]; then
                git clone https://github.com/VundleVim/Vundle.vim.git "$_vundle_path"
            fi
            echo 'Please ignore any error related to color scheme'
            vim +PluginInstall +qall
        fi
    fi
fi

if ask_yesno 'Install ~/.gitconfig? This will not overwrite anything by default'; then
    if [[ -f "$HOME/.gitconfig" ]]; then
        if ask_yesno '~/.gitconfig exists, append to it?'; then
            cat "$_pwd/git/gitconfig" >> "$HOME/.gitconfig"
        elif ! ask_yesno 'keep it? n for overwrite it'; then
            cp -fv "$_pwd/git/gitconfig" "$HOME/.gitconfig"
        fi
    else
        cp -fv "$_pwd/git/gitconfig" "$HOME/.gitconfig"
    fi
fi

if ask_yesno 'Install ~/.tmux.conf? This will overwrite it if exists'; then
    $_install "$_pwd/tmux/tmux.conf" "$HOME/.tmux.conf"
fi

if ask_yesno 'Install ~/.Xresources? This will overwrite it if exists'; then
    $_install "$_pwd/xrdb/Xresources" "$HOME/.Xresources"
    if type xrdb > /dev/null 2>&1; then
        echo 'Refreshing X resource database'
        xrdb "$HOME/.Xresources"
    else
        echo 'xrdb not found, skipping'
    fi
fi
