set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

so ~/.vimrc-commonplugins

call vundle#end()

filetype plugin indent on

so ~/.vimrc-common
if has('gui_running')
    so ~/.vimrc-gui
endif
