## helper
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g DN=/dev/null
alias -g NUL="> /dev/null 2>&1"
alias -g NE="2> /dev/null"

## macOS coreutils
if isdarwin && type gls NUL; then
    # assume that if gls is installed, the entire coreutils is available

    # backup all builtin commands
    alias 'bsd-base64'='/usr/bin/base64'
    alias 'bsd-basename'='/usr/bin/basename'
    alias 'bsd-cat'='/bin/cat'
    alias 'bsd-chgrp'='/usr/bin/chgrp'
    alias 'bsd-chmod'='/bin/chmod'
    alias 'bsd-chown'='/usr/sbin/chown'
    alias 'bsd-chroot'='/usr/sbin/chroot'
    alias 'bsd-cksum'='/usr/bin/cksum'
    alias 'bsd-comm'='/usr/bin/comm'
    alias 'bsd-cp'='/bin/cp'
    alias 'bsd-csplit'='/usr/bin/csplit'
    alias 'bsd-cut'='/usr/bin/cut'
    alias 'bsd-date'='/bin/date'
    alias 'bsd-dd'='/bin/dd'
    alias 'bsd-df'='/bin/df'
    alias 'bsd-dirname'='/usr/bin/dirname'
    alias 'bsd-du'='/usr/bin/du'
    alias 'bsd-echo'='/bin/echo'
    alias 'bsd-env'='/usr/bin/env'
    alias 'bsd-expand'='/usr/bin/expand'
    alias 'bsd-expr'='/bin/expr'
    alias 'bsd-false'='/usr/bin/false'
    alias 'bsd-fmt'='/usr/bin/fmt'
    alias 'bsd-fold'='/usr/bin/fold'
    alias 'bsd-groups'='/usr/bin/groups'
    alias 'bsd-head'='/usr/bin/head'
    alias 'bsd-id'='/usr/bin/id'
    alias 'bsd-install'='/usr/bin/install'
    alias 'bsd-join'='/usr/bin/join'
    alias 'bsd-kill'='/bin/kill'
    alias 'bsd-link'='/bin/link'
    alias 'bsd-ln'='/bin/ln'
    alias 'bsd-logname'='/usr/bin/logname'
    alias 'bsd-ls'='/bin/ls'
    alias 'bsd-mkdir'='/bin/mkdir'
    alias 'bsd-mkfifo'='/usr/bin/mkfifo'
    alias 'bsd-mknod'='/sbin/mknod'
    alias 'bsd-mktemp'='/usr/bin/mktemp'
    alias 'bsd-mv'='/bin/mv'
    alias 'bsd-nice'='/usr/bin/nice'
    alias 'bsd-nl'='/usr/bin/nl'
    alias 'bsd-nohup'='/usr/bin/nohup'
    alias 'bsd-od'='/usr/bin/od'
    alias 'bsd-paste'='/usr/bin/paste'
    alias 'bsd-pathchk'='/usr/bin/pathchk'
    alias 'bsd-pr'='/usr/bin/pr'
    alias 'bsd-printenv'='/usr/bin/printenv'
    alias 'bsd-printf'='/usr/bin/printf'
    alias 'bsd-pwd'='/bin/pwd'
    alias 'bsd-readlink'='/usr/bin/readlink'
    alias 'bsd-rm'='/bin/rm'
    alias 'bsd-rmdir'='/bin/rmdir'
    alias 'bsd-seq'='/usr/bin/seq'
    alias 'bsd-sleep'='/bin/sleep'
    alias 'bsd-sort'='/usr/bin/sort'
    alias 'bsd-split'='/usr/bin/split'
    alias 'bsd-stat'='/usr/bin/stat'
    alias 'bsd-stty'='/bin/stty'
    alias 'bsd-sum'='/usr/bin/sum'
    alias 'bsd-sync'='/bin/sync'
    alias 'bsd-tail'='/usr/bin/tail'
    alias 'bsd-tee'='/usr/bin/tee'
    alias 'bsd-test'='/bin/test'
    alias 'bsd-touch'='/usr/bin/touch'
    alias 'bsd-tr'='/usr/bin/tr'
    alias 'bsd-true'='/usr/bin/true'
    alias 'bsd-tsort'='/usr/bin/tsort'
    alias 'bsd-tty'='/usr/bin/tty'
    alias 'bsd-uname'='/usr/bin/uname'
    alias 'bsd-unexpand'='/usr/bin/unexpand'
    alias 'bsd-uniq'='/usr/bin/uniq'
    alias 'bsd-unlink'='/bin/unlink'
    alias 'bsd-uptime'='/usr/bin/uptime'
    alias 'bsd-users'='/usr/bin/users'
    alias 'bsd-wc'='/usr/bin/wc'
    alias 'bsd-who'='/usr/bin/who'
    alias 'bsd-whoami'='/usr/bin/whoami'
    alias 'bsd-yes'='/usr/bin/yes'

    # and replace them with coreutils ones
    type '/usr/local/bin/gb2sum' NUL && alias 'b2sum'='/usr/local/bin/gb2sum'
    type '/usr/local/bin/gbase32' NUL && alias 'base32'='/usr/local/bin/gbase32'
    type '/usr/local/bin/gbase64' NUL && alias 'base64'='/usr/local/bin/gbase64'
    type '/usr/local/bin/gbasename' NUL && alias 'basename'='/usr/local/bin/gbasename'
    type '/usr/local/bin/gcat' NUL && alias 'cat'='/usr/local/bin/gcat'
    type '/usr/local/bin/gchcon' NUL && alias 'chcon'='/usr/local/bin/gchcon'
    type '/usr/local/bin/gchgrp' NUL && alias 'chgrp'='/usr/local/bin/gchgrp'
    type '/usr/local/bin/gchmod' NUL && alias 'chmod'='/usr/local/bin/gchmod'
    type '/usr/local/bin/gchown' NUL && alias 'chown'='/usr/local/bin/gchown'
    type '/usr/local/bin/gchroot' NUL && alias 'chroot'='/usr/local/bin/gchroot'
    type '/usr/local/bin/gcksum' NUL && alias 'cksum'='/usr/local/bin/gcksum'
    type '/usr/local/bin/gcomm' NUL && alias 'comm'='/usr/local/bin/gcomm'
    type '/usr/local/bin/gcp' NUL && alias 'cp'='/usr/local/bin/gcp'
    type '/usr/local/bin/gcsplit' NUL && alias 'csplit'='/usr/local/bin/gcsplit'
    type '/usr/local/bin/gcut' NUL && alias 'cut'='/usr/local/bin/gcut'
    type '/usr/local/bin/gdate' NUL && alias 'date'='/usr/local/bin/gdate'
    type '/usr/local/bin/gdd' NUL && alias 'dd'='/usr/local/bin/gdd'
    type '/usr/local/bin/gdf' NUL && alias 'df'='/usr/local/bin/gdf'
    type '/usr/local/bin/gdir' NUL && alias 'dir'='/usr/local/bin/gdir'
    type '/usr/local/bin/gdircolors' NUL && alias 'dircolors'='/usr/local/bin/gdircolors'
    type '/usr/local/bin/gdirname' NUL && alias 'dirname'='/usr/local/bin/gdirname'
    type '/usr/local/bin/gdu' NUL && alias 'du'='/usr/local/bin/gdu'
    type '/usr/local/bin/gecho' NUL && alias 'echo'='/usr/local/bin/gecho'
    type '/usr/local/bin/genv' NUL && alias 'env'='/usr/local/bin/genv'
    type '/usr/local/bin/gexpand' NUL && alias 'expand'='/usr/local/bin/gexpand'
    type '/usr/local/bin/gexpr' NUL && alias 'expr'='/usr/local/bin/gexpr'
    type '/usr/local/bin/gfactor' NUL && alias 'factor'='/usr/local/bin/gfactor'
    type '/usr/local/bin/gfalse' NUL && alias 'false'='/usr/local/bin/gfalse'
    type '/usr/local/bin/gfmt' NUL && alias 'fmt'='/usr/local/bin/gfmt'
    type '/usr/local/bin/gfold' NUL && alias 'fold'='/usr/local/bin/gfold'
    type '/usr/local/bin/ggroups' NUL && alias 'groups'='/usr/local/bin/ggroups'
    type '/usr/local/bin/ghead' NUL && alias 'head'='/usr/local/bin/ghead'
    type '/usr/local/bin/ghostid' NUL && alias 'hostid'='/usr/local/bin/ghostid'
    type '/usr/local/bin/gid' NUL && alias 'id'='/usr/local/bin/gid'
    type '/usr/local/bin/ginstall' NUL && alias 'install'='/usr/local/bin/ginstall'
    type '/usr/local/bin/gjoin' NUL && alias 'join'='/usr/local/bin/gjoin'
    type '/usr/local/bin/gkill' NUL && alias 'kill'='/usr/local/bin/gkill'
    type '/usr/local/bin/glink' NUL && alias 'link'='/usr/local/bin/glink'
    type '/usr/local/bin/gln' NUL && alias 'ln'='/usr/local/bin/gln'
    type '/usr/local/bin/glogname' NUL && alias 'logname'='/usr/local/bin/glogname'
    type '/usr/local/bin/gls' NUL && alias 'ls'='/usr/local/bin/gls'
    type '/usr/local/bin/gmd5sum' NUL && alias 'md5sum'='/usr/local/bin/gmd5sum'
    type '/usr/local/bin/gmkdir' NUL && alias 'mkdir'='/usr/local/bin/gmkdir'
    type '/usr/local/bin/gmkfifo' NUL && alias 'mkfifo'='/usr/local/bin/gmkfifo'
    type '/usr/local/bin/gmknod' NUL && alias 'mknod'='/usr/local/bin/gmknod'
    type '/usr/local/bin/gmktemp' NUL && alias 'mktemp'='/usr/local/bin/gmktemp'
    type '/usr/local/bin/gmv' NUL && alias 'mv'='/usr/local/bin/gmv'
    type '/usr/local/bin/gnice' NUL && alias 'nice'='/usr/local/bin/gnice'
    type '/usr/local/bin/gnl' NUL && alias 'nl'='/usr/local/bin/gnl'
    type '/usr/local/bin/gnohup' NUL && alias 'nohup'='/usr/local/bin/gnohup'
    type '/usr/local/bin/gnproc' NUL && alias 'nproc'='/usr/local/bin/gnproc'
    type '/usr/local/bin/gnumfmt' NUL && alias 'numfmt'='/usr/local/bin/gnumfmt'
    type '/usr/local/bin/god' NUL && alias 'od'='/usr/local/bin/god'
    type '/usr/local/bin/gpaste' NUL && alias 'paste'='/usr/local/bin/gpaste'
    type '/usr/local/bin/gpathchk' NUL && alias 'pathchk'='/usr/local/bin/gpathchk'
    type '/usr/local/bin/gpinky' NUL && alias 'pinky'='/usr/local/bin/gpinky'
    type '/usr/local/bin/gpr' NUL && alias 'pr'='/usr/local/bin/gpr'
    type '/usr/local/bin/gprintenv' NUL && alias 'printenv'='/usr/local/bin/gprintenv'
    type '/usr/local/bin/gprintf' NUL && alias 'printf'='/usr/local/bin/gprintf'
    type '/usr/local/bin/gptx' NUL && alias 'ptx'='/usr/local/bin/gptx'
    type '/usr/local/bin/gpwd' NUL && alias 'pwd'='/usr/local/bin/gpwd'
    type '/usr/local/bin/greadlink' NUL && alias 'readlink'='/usr/local/bin/greadlink'
    type '/usr/local/bin/grealpath' NUL && alias 'realpath'='/usr/local/bin/grealpath'
    type '/usr/local/bin/grm' NUL && alias 'rm'='/usr/local/bin/grm'
    type '/usr/local/bin/grmdir' NUL && alias 'rmdir'='/usr/local/bin/grmdir'
    type '/usr/local/bin/gruncon' NUL && alias 'runcon'='/usr/local/bin/gruncon'
    type '/usr/local/bin/gseq' NUL && alias 'seq'='/usr/local/bin/gseq'
    type '/usr/local/bin/gsha1sum' NUL && alias 'sha1sum'='/usr/local/bin/gsha1sum'
    type '/usr/local/bin/gsha224sum' NUL && alias 'sha224sum'='/usr/local/bin/gsha224sum'
    type '/usr/local/bin/gsha256sum' NUL && alias 'sha256sum'='/usr/local/bin/gsha256sum'
    type '/usr/local/bin/gsha384sum' NUL && alias 'sha384sum'='/usr/local/bin/gsha384sum'
    type '/usr/local/bin/gsha512sum' NUL && alias 'sha512sum'='/usr/local/bin/gsha512sum'
    type '/usr/local/bin/gshred' NUL && alias 'shred'='/usr/local/bin/gshred'
    type '/usr/local/bin/gshuf' NUL && alias 'shuf'='/usr/local/bin/gshuf'
    type '/usr/local/bin/gsleep' NUL && alias 'sleep'='/usr/local/bin/gsleep'
    type '/usr/local/bin/gsort' NUL && alias 'sort'='/usr/local/bin/gsort'
    type '/usr/local/bin/gsplit' NUL && alias 'split'='/usr/local/bin/gsplit'
    type '/usr/local/bin/gstat' NUL && alias 'stat'='/usr/local/bin/gstat'
    type '/usr/local/bin/gstdbuf' NUL && alias 'stdbuf'='/usr/local/bin/gstdbuf'
    type '/usr/local/bin/gstty' NUL && alias 'stty'='/usr/local/bin/gstty'
    type '/usr/local/bin/gsum' NUL && alias 'sum'='/usr/local/bin/gsum'
    type '/usr/local/bin/gsync' NUL && alias 'sync'='/usr/local/bin/gsync'
    type '/usr/local/bin/gtac' NUL && alias 'tac'='/usr/local/bin/gtac'
    type '/usr/local/bin/gtail' NUL && alias 'tail'='/usr/local/bin/gtail'
    type '/usr/local/bin/gtee' NUL && alias 'tee'='/usr/local/bin/gtee'
    type '/usr/local/bin/gtest' NUL && alias 'test'='/usr/local/bin/gtest'
    type '/usr/local/bin/gtimeout' NUL && alias 'timeout'='/usr/local/bin/gtimeout'
    type '/usr/local/bin/gtouch' NUL && alias 'touch'='/usr/local/bin/gtouch'
    type '/usr/local/bin/gtr' NUL && alias 'tr'='/usr/local/bin/gtr'
    type '/usr/local/bin/gtrue' NUL && alias 'true'='/usr/local/bin/gtrue'
    type '/usr/local/bin/gtruncate' NUL && alias 'truncate'='/usr/local/bin/gtruncate'
    type '/usr/local/bin/gtsort' NUL && alias 'tsort'='/usr/local/bin/gtsort'
    type '/usr/local/bin/gtty' NUL && alias 'tty'='/usr/local/bin/gtty'
    type '/usr/local/bin/guname' NUL && alias 'uname'='/usr/local/bin/guname'
    type '/usr/local/bin/gunexpand' NUL && alias 'unexpand'='/usr/local/bin/gunexpand'
    type '/usr/local/bin/guniq' NUL && alias 'uniq'='/usr/local/bin/guniq'
    type '/usr/local/bin/gunlink' NUL && alias 'unlink'='/usr/local/bin/gunlink'
    type '/usr/local/bin/guptime' NUL && alias 'uptime'='/usr/local/bin/guptime'
    type '/usr/local/bin/gusers' NUL && alias 'users'='/usr/local/bin/gusers'
    type '/usr/local/bin/gvdir' NUL && alias 'vdir'='/usr/local/bin/gvdir'
    type '/usr/local/bin/gwc' NUL && alias 'wc'='/usr/local/bin/gwc'
    type '/usr/local/bin/gwho' NUL && alias 'who'='/usr/local/bin/gwho'
    type '/usr/local/bin/gwhoami' NUL && alias 'whoami'='/usr/local/bin/gwhoami'
    type '/usr/local/bin/gyes' NUL && alias 'yes'='/usr/local/bin/gyes'
fi

## Enable ls coloring
if ismsys; then
    alias ls='ls --color=auto "--ignore=NTUSER.DAT*" "--ignore=ntuser.dat*" --ignore=ntuser.ini'
elif islinux; then
    alias ls='ls --color=auto'
elif isdarwin && type gls NUL; then
    alias ls="$(which gls) --color=auto"
fi

## ls related aliases
alias l='ls -lah'
alias l.='ls -d .*'
alias la='ls -lAh'
alias ll='ls -lh'
alias lsa='ls -lah'

## grep related aliases
alias grep="grep --color=auto"
alias egrep='grep -E'
alias fgrep='grep -F'

## docker
if ! isdarwin && type sudo NUL && type docker NUL; then
    alias docker-orig="$(which docker)"
    alias docker='sudo docker'
fi

## others
function _regist_zsh_custom_aliases() {
    local _zsh_custom_dir="${funcsourcetrace[1]%/*/*}"
    alias cdz="cd '$_zsh_custom_dir'"
    alias vimz="vim '$_zsh_custom_dir/custom.zsh'"
    alias cdmod="cd '$_zsh_custom_dir/mod'"
    alias vimmod="vim '$_zsh_custom_dir/modules.zsh'"
    alias vimcomp="vim '$_zsh_custom_dir/completions.zsh'"
}
_regist_zsh_custom_aliases
unfunction _regist_zsh_custom_aliases
